//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_demo_app.TP4 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransportRequest", Namespace="http://transport.merchantware.net/v4/")]
    [System.SerializableAttribute()]
    public partial class TransportRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionTypeField;
        
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClerkIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DbaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoftwareNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoftwareVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardholderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RedirectLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        private bool ForceDuplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoNumberField;
        
        private decimal TaxAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private POS_demo_app.TP4.DisplayColors DisplayColorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private POS_demo_app.TP4.DisplayOptions DisplayOptionsField;
        
        private POS_demo_app.TP4.EntryMode EntryModeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransactionType {
            get {
                return this.TransactionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTypeField, value) != true)) {
                    this.TransactionTypeField = value;
                    this.RaisePropertyChanged("TransactionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ClerkId {
            get {
                return this.ClerkIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClerkIdField, value) != true)) {
                    this.ClerkIdField = value;
                    this.RaisePropertyChanged("ClerkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dba {
            get {
                return this.DbaField;
            }
            set {
                if ((object.ReferenceEquals(this.DbaField, value) != true)) {
                    this.DbaField = value;
                    this.RaisePropertyChanged("Dba");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SoftwareName {
            get {
                return this.SoftwareNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SoftwareNameField, value) != true)) {
                    this.SoftwareNameField = value;
                    this.RaisePropertyChanged("SoftwareName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SoftwareVersion {
            get {
                return this.SoftwareVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.SoftwareVersionField, value) != true)) {
                    this.SoftwareVersionField = value;
                    this.RaisePropertyChanged("SoftwareVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Cardholder {
            get {
                return this.CardholderField;
            }
            set {
                if ((object.ReferenceEquals(this.CardholderField, value) != true)) {
                    this.CardholderField = value;
                    this.RaisePropertyChanged("Cardholder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string LogoLocation {
            get {
                return this.LogoLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoLocationField, value) != true)) {
                    this.LogoLocationField = value;
                    this.RaisePropertyChanged("LogoLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string RedirectLocation {
            get {
                return this.RedirectLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.RedirectLocationField, value) != true)) {
                    this.RedirectLocationField = value;
                    this.RaisePropertyChanged("RedirectLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool ForceDuplicate {
            get {
                return this.ForceDuplicateField;
            }
            set {
                if ((this.ForceDuplicateField.Equals(value) != true)) {
                    this.ForceDuplicateField = value;
                    this.RaisePropertyChanged("ForceDuplicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CustomerCode {
            get {
                return this.CustomerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCodeField, value) != true)) {
                    this.CustomerCodeField = value;
                    this.RaisePropertyChanged("CustomerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string PoNumber {
            get {
                return this.PoNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PoNumberField, value) != true)) {
                    this.PoNumberField = value;
                    this.RaisePropertyChanged("PoNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public decimal TaxAmount {
            get {
                return this.TaxAmountField;
            }
            set {
                if ((this.TaxAmountField.Equals(value) != true)) {
                    this.TaxAmountField = value;
                    this.RaisePropertyChanged("TaxAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public POS_demo_app.TP4.DisplayColors DisplayColors {
            get {
                return this.DisplayColorsField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayColorsField, value) != true)) {
                    this.DisplayColorsField = value;
                    this.RaisePropertyChanged("DisplayColors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public POS_demo_app.TP4.DisplayOptions DisplayOptions {
            get {
                return this.DisplayOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayOptionsField, value) != true)) {
                    this.DisplayOptionsField = value;
                    this.RaisePropertyChanged("DisplayOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public POS_demo_app.TP4.EntryMode EntryMode {
            get {
                return this.EntryModeField;
            }
            set {
                if ((this.EntryModeField.Equals(value) != true)) {
                    this.EntryModeField = value;
                    this.RaisePropertyChanged("EntryMode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisplayColors", Namespace="http://transport.merchantware.net/v4/")]
    [System.SerializableAttribute()]
    public partial class DisplayColors : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScreenBackgroundColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContainerBackgroundColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContainerFontColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContainerHelpFontColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContainerBorderColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoBackgroundColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoBorderColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TooltipBackgroundColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TooltipBorderColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TooltipFontColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextboxBackgroundColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextboxBorderColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextboxFocusBackgroundColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextboxFocusBorderColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextboxFontColorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ScreenBackgroundColor {
            get {
                return this.ScreenBackgroundColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ScreenBackgroundColorField, value) != true)) {
                    this.ScreenBackgroundColorField = value;
                    this.RaisePropertyChanged("ScreenBackgroundColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ContainerBackgroundColor {
            get {
                return this.ContainerBackgroundColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainerBackgroundColorField, value) != true)) {
                    this.ContainerBackgroundColorField = value;
                    this.RaisePropertyChanged("ContainerBackgroundColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ContainerFontColor {
            get {
                return this.ContainerFontColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainerFontColorField, value) != true)) {
                    this.ContainerFontColorField = value;
                    this.RaisePropertyChanged("ContainerFontColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ContainerHelpFontColor {
            get {
                return this.ContainerHelpFontColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainerHelpFontColorField, value) != true)) {
                    this.ContainerHelpFontColorField = value;
                    this.RaisePropertyChanged("ContainerHelpFontColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ContainerBorderColor {
            get {
                return this.ContainerBorderColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainerBorderColorField, value) != true)) {
                    this.ContainerBorderColorField = value;
                    this.RaisePropertyChanged("ContainerBorderColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string LogoBackgroundColor {
            get {
                return this.LogoBackgroundColorField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoBackgroundColorField, value) != true)) {
                    this.LogoBackgroundColorField = value;
                    this.RaisePropertyChanged("LogoBackgroundColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string LogoBorderColor {
            get {
                return this.LogoBorderColorField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoBorderColorField, value) != true)) {
                    this.LogoBorderColorField = value;
                    this.RaisePropertyChanged("LogoBorderColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TooltipBackgroundColor {
            get {
                return this.TooltipBackgroundColorField;
            }
            set {
                if ((object.ReferenceEquals(this.TooltipBackgroundColorField, value) != true)) {
                    this.TooltipBackgroundColorField = value;
                    this.RaisePropertyChanged("TooltipBackgroundColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TooltipBorderColor {
            get {
                return this.TooltipBorderColorField;
            }
            set {
                if ((object.ReferenceEquals(this.TooltipBorderColorField, value) != true)) {
                    this.TooltipBorderColorField = value;
                    this.RaisePropertyChanged("TooltipBorderColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TooltipFontColor {
            get {
                return this.TooltipFontColorField;
            }
            set {
                if ((object.ReferenceEquals(this.TooltipFontColorField, value) != true)) {
                    this.TooltipFontColorField = value;
                    this.RaisePropertyChanged("TooltipFontColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string TextboxBackgroundColor {
            get {
                return this.TextboxBackgroundColorField;
            }
            set {
                if ((object.ReferenceEquals(this.TextboxBackgroundColorField, value) != true)) {
                    this.TextboxBackgroundColorField = value;
                    this.RaisePropertyChanged("TextboxBackgroundColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string TextboxBorderColor {
            get {
                return this.TextboxBorderColorField;
            }
            set {
                if ((object.ReferenceEquals(this.TextboxBorderColorField, value) != true)) {
                    this.TextboxBorderColorField = value;
                    this.RaisePropertyChanged("TextboxBorderColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TextboxFocusBackgroundColor {
            get {
                return this.TextboxFocusBackgroundColorField;
            }
            set {
                if ((object.ReferenceEquals(this.TextboxFocusBackgroundColorField, value) != true)) {
                    this.TextboxFocusBackgroundColorField = value;
                    this.RaisePropertyChanged("TextboxFocusBackgroundColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string TextboxFocusBorderColor {
            get {
                return this.TextboxFocusBorderColorField;
            }
            set {
                if ((object.ReferenceEquals(this.TextboxFocusBorderColorField, value) != true)) {
                    this.TextboxFocusBorderColorField = value;
                    this.RaisePropertyChanged("TextboxFocusBorderColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string TextboxFontColor {
            get {
                return this.TextboxFontColorField;
            }
            set {
                if ((object.ReferenceEquals(this.TextboxFontColorField, value) != true)) {
                    this.TextboxFontColorField = value;
                    this.RaisePropertyChanged("TextboxFontColor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisplayOptions", Namespace="http://transport.merchantware.net/v4/")]
    [System.SerializableAttribute()]
    public partial class DisplayOptions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool AlignLeftField;
        
        private bool NoCardNumberMaskField;
        
        private bool HideDetailsField;
        
        private bool HideDowngradeMessageField;
        
        private bool HideMessageField;
        
        private bool HideTooltipsField;
        
        private bool UseNativeButtonsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool AlignLeft {
            get {
                return this.AlignLeftField;
            }
            set {
                if ((this.AlignLeftField.Equals(value) != true)) {
                    this.AlignLeftField = value;
                    this.RaisePropertyChanged("AlignLeft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool NoCardNumberMask {
            get {
                return this.NoCardNumberMaskField;
            }
            set {
                if ((this.NoCardNumberMaskField.Equals(value) != true)) {
                    this.NoCardNumberMaskField = value;
                    this.RaisePropertyChanged("NoCardNumberMask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool HideDetails {
            get {
                return this.HideDetailsField;
            }
            set {
                if ((this.HideDetailsField.Equals(value) != true)) {
                    this.HideDetailsField = value;
                    this.RaisePropertyChanged("HideDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool HideDowngradeMessage {
            get {
                return this.HideDowngradeMessageField;
            }
            set {
                if ((this.HideDowngradeMessageField.Equals(value) != true)) {
                    this.HideDowngradeMessageField = value;
                    this.RaisePropertyChanged("HideDowngradeMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool HideMessage {
            get {
                return this.HideMessageField;
            }
            set {
                if ((this.HideMessageField.Equals(value) != true)) {
                    this.HideMessageField = value;
                    this.RaisePropertyChanged("HideMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool HideTooltips {
            get {
                return this.HideTooltipsField;
            }
            set {
                if ((this.HideTooltipsField.Equals(value) != true)) {
                    this.HideTooltipsField = value;
                    this.RaisePropertyChanged("HideTooltips");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool UseNativeButtons {
            get {
                return this.UseNativeButtonsField;
            }
            set {
                if ((this.UseNativeButtonsField.Equals(value) != true)) {
                    this.UseNativeButtonsField = value;
                    this.RaisePropertyChanged("UseNativeButtons");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntryMode", Namespace="http://transport.merchantware.net/v4/")]
    public enum EntryMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Keyed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Swiped = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeyedSwiped = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransportResponse", Namespace="http://transport.merchantware.net/v4/")]
    [System.SerializableAttribute()]
    public partial class TransportResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransportKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidationKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private POS_demo_app.TP4.Message[] MessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransportKey {
            get {
                return this.TransportKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.TransportKeyField, value) != true)) {
                    this.TransportKeyField = value;
                    this.RaisePropertyChanged("TransportKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ValidationKey {
            get {
                return this.ValidationKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationKeyField, value) != true)) {
                    this.ValidationKeyField = value;
                    this.RaisePropertyChanged("ValidationKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public POS_demo_app.TP4.Message[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://transport.merchantware.net/v4/")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InformationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Information {
            get {
                return this.InformationField;
            }
            set {
                if ((object.ReferenceEquals(this.InformationField, value) != true)) {
                    this.InformationField = value;
                    this.RaisePropertyChanged("Information");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://transport.merchantware.net/v4/", ConfigurationName="TP4.TransportServiceSoap")]
    public interface TransportServiceSoap {
        
        // CODEGEN: Generating message contract since element name merchantName from namespace http://transport.merchantware.net/v4/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://transport.merchantware.net/v4/CreateTransaction", ReplyAction="*")]
        POS_demo_app.TP4.CreateTransactionResponse CreateTransaction(POS_demo_app.TP4.CreateTransactionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTransaction", Namespace="http://transport.merchantware.net/v4/", Order=0)]
        public POS_demo_app.TP4.CreateTransactionRequestBody Body;
        
        public CreateTransactionRequest() {
        }
        
        public CreateTransactionRequest(POS_demo_app.TP4.CreateTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://transport.merchantware.net/v4/")]
    public partial class CreateTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string merchantSiteId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string merchantKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public POS_demo_app.TP4.TransportRequest request;
        
        public CreateTransactionRequestBody() {
        }
        
        public CreateTransactionRequestBody(string merchantName, string merchantSiteId, string merchantKey, POS_demo_app.TP4.TransportRequest request) {
            this.merchantName = merchantName;
            this.merchantSiteId = merchantSiteId;
            this.merchantKey = merchantKey;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTransactionResponse", Namespace="http://transport.merchantware.net/v4/", Order=0)]
        public POS_demo_app.TP4.CreateTransactionResponseBody Body;
        
        public CreateTransactionResponse() {
        }
        
        public CreateTransactionResponse(POS_demo_app.TP4.CreateTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://transport.merchantware.net/v4/")]
    public partial class CreateTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POS_demo_app.TP4.TransportResponse CreateTransactionResult;
        
        public CreateTransactionResponseBody() {
        }
        
        public CreateTransactionResponseBody(POS_demo_app.TP4.TransportResponse CreateTransactionResult) {
            this.CreateTransactionResult = CreateTransactionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransportServiceSoapChannel : POS_demo_app.TP4.TransportServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransportServiceSoapClient : System.ServiceModel.ClientBase<POS_demo_app.TP4.TransportServiceSoap>, POS_demo_app.TP4.TransportServiceSoap {
        
        public TransportServiceSoapClient() {
        }
        
        public TransportServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransportServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_demo_app.TP4.CreateTransactionResponse POS_demo_app.TP4.TransportServiceSoap.CreateTransaction(POS_demo_app.TP4.CreateTransactionRequest request) {
            return base.Channel.CreateTransaction(request);
        }
        
        public POS_demo_app.TP4.TransportResponse CreateTransaction(string merchantName, string merchantSiteId, string merchantKey, POS_demo_app.TP4.TransportRequest request) {
            POS_demo_app.TP4.CreateTransactionRequest inValue = new POS_demo_app.TP4.CreateTransactionRequest();
            inValue.Body = new POS_demo_app.TP4.CreateTransactionRequestBody();
            inValue.Body.merchantName = merchantName;
            inValue.Body.merchantSiteId = merchantSiteId;
            inValue.Body.merchantKey = merchantKey;
            inValue.Body.request = request;
            POS_demo_app.TP4.CreateTransactionResponse retVal = ((POS_demo_app.TP4.TransportServiceSoap)(this)).CreateTransaction(inValue);
            return retVal.Body.CreateTransactionResult;
        }
    }
}
